import Head from "next/head";
import Nav from "~/components/home/Nav";


export default function Home() {
  return (
    <>
      <Head>
        <title>todo daily</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewpoint" content="width=device-width, initial-scale=1.0"></meta>
      </Head>
      <div className="h-screen w-full sm:container m-auto">
        <Nav />
      </div>
    </>
  );
}
